export interface WidgetTheme {
  name: string;
  label: string;
  preview: string;
  config: Record<string, string | number>;
}

export const WIDGET_THEMES: WidgetTheme[] = [
  {
    name: "custom",
    label: "Personalizado",
    preview: "🎨",
    config: {},
  },
  {
    name: "default",
    label: "Jandosoft",
    preview: "🔴",
    config: {
      primaryColor: "#dc2626",
      secondaryColor: "#f5f5f5",
      textColor: "#09090b",
      headerBgColor: "#dc2626",
      headerTextColor: "#ffffff",
      botBubbleColor: "#f4f4f5",
      userBubbleColor: "#dc2626",
      chatBgColor: "#f9fafb",
      inputBgColor: "#ffffff",
      inputBorderColor: "#e4e4e7",
      inputFocusColor: "#dc2626",
      inputTextColor: "#18181b",
      botTextColor: "#18181b",
      userTextColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderRadius: 16,
      inputRadius: 12,
      bubbleRadius: 16,
      shadow: "0 8px 40px rgba(0,0,0,0.12)",
    },
  },
  {
    name: "dark",
    label: "Dark",
    preview: "🌙",
    config: {
      primaryColor: "#8b5cf6",
      secondaryColor: "#1e1e2e",
      textColor: "#e4e4e7",
      headerBgColor: "#1e1e2e",
      headerTextColor: "#e4e4e7",
      botBubbleColor: "#2a2a3c",
      userBubbleColor: "#8b5cf6",
      chatBgColor: "#14141f",
      inputBgColor: "#1e1e2e",
      inputBorderColor: "#333347",
      inputFocusColor: "#8b5cf6",
      inputTextColor: "#e4e4e7",
      botTextColor: "#d4d4d8",
      userTextColor: "#ffffff",
      borderColor: "#333347",
      borderRadius: 16,
      inputRadius: 12,
      bubbleRadius: 16,
      shadow: "0 8px 40px rgba(0,0,0,0.5)",
    },
  },
  {
    name: "light",
    label: "Light",
    preview: "☀️",
    config: {
      primaryColor: "#2563eb",
      secondaryColor: "#f8fafc",
      textColor: "#0f172a",
      headerBgColor: "#2563eb",
      headerTextColor: "#ffffff",
      botBubbleColor: "#f1f5f9",
      userBubbleColor: "#2563eb",
      chatBgColor: "#ffffff",
      inputBgColor: "#ffffff",
      inputBorderColor: "#e2e8f0",
      inputFocusColor: "#2563eb",
      inputTextColor: "#0f172a",
      botTextColor: "#334155",
      userTextColor: "#ffffff",
      borderColor: "#e2e8f0",
      borderRadius: 12,
      inputRadius: 10,
      bubbleRadius: 12,
      shadow: "0 4px 24px rgba(0,0,0,0.08)",
    },
  },
  {
    name: "chatgpt",
    label: "ChatGPT",
    preview: "🤖",
    config: {
      primaryColor: "#10a37f",
      secondaryColor: "#202123",
      textColor: "#ececf1",
      headerBgColor: "#202123",
      headerTextColor: "#ececf1",
      botBubbleColor: "#202123",
      userBubbleColor: "#343541",
      chatBgColor: "#343541",
      inputBgColor: "#40414f",
      inputBorderColor: "#565869",
      inputFocusColor: "#10a37f",
      inputTextColor: "#ececf1",
      botTextColor: "#d1d5db",
      userTextColor: "#ececf1",
      borderColor: "#565869",
      borderRadius: 12,
      inputRadius: 10,
      bubbleRadius: 12,
      shadow: "0 8px 32px rgba(0,0,0,0.4)",
    },
  },
  {
    name: "whatsapp",
    label: "WhatsApp",
    preview: "💬",
    config: {
      primaryColor: "#25d366",
      secondaryColor: "#111b21",
      textColor: "#e9edef",
      headerBgColor: "#1f2c34",
      headerTextColor: "#e9edef",
      botBubbleColor: "#1f2c34",
      userBubbleColor: "#005c4b",
      chatBgColor: "#0b141a",
      inputBgColor: "#202c33",
      inputBorderColor: "#313d45",
      inputFocusColor: "#25d366",
      inputTextColor: "#d1d7dc",
      botTextColor: "#d1d7dc",
      userTextColor: "#e9edef",
      borderColor: "#313d45",
      borderRadius: 12,
      inputRadius: 8,
      bubbleRadius: 8,
      shadow: "0 8px 32px rgba(0,0,0,0.4)",
    },
  },
  {
    name: "discord",
    label: "Discord",
    preview: "🎮",
    config: {
      primaryColor: "#5865f2",
      secondaryColor: "#2b2d31",
      textColor: "#dbdee1",
      headerBgColor: "#1e1f22",
      headerTextColor: "#f2f3f5",
      botBubbleColor: "#2b2d31",
      userBubbleColor: "#5865f2",
      chatBgColor: "#313338",
      inputBgColor: "#383a40",
      inputBorderColor: "#4e5058",
      inputFocusColor: "#5865f2",
      inputTextColor: "#dbdee1",
      botTextColor: "#b5bac1",
      userTextColor: "#ffffff",
      borderColor: "#4e5058",
      borderRadius: 8,
      inputRadius: 8,
      bubbleRadius: 8,
      shadow: "0 8px 32px rgba(0,0,0,0.4)",
    },
  },
  {
    name: "minimal",
    label: "Minimal",
    preview: "◻️",
    config: {
      primaryColor: "#171717",
      secondaryColor: "#fafafa",
      textColor: "#171717",
      headerBgColor: "#ffffff",
      headerTextColor: "#171717",
      botBubbleColor: "#f5f5f5",
      userBubbleColor: "#171717",
      chatBgColor: "#ffffff",
      inputBgColor: "#ffffff",
      inputBorderColor: "#e5e5e5",
      inputFocusColor: "#171717",
      inputTextColor: "#171717",
      botTextColor: "#404040",
      userTextColor: "#ffffff",
      borderColor: "#e5e5e5",
      borderRadius: 4,
      inputRadius: 4,
      bubbleRadius: 4,
      shadow: "0 1px 3px rgba(0,0,0,0.06)",
    },
  },
  {
    name: "luxury",
    label: "Luxury",
    preview: "✨",
    config: {
      primaryColor: "#b8860b",
      secondaryColor: "#1a1a1a",
      textColor: "#f5f0e8",
      headerBgColor: "#0d0d0d",
      headerTextColor: "#d4af37",
      botBubbleColor: "#1a1a1a",
      userBubbleColor: "#2a1f0a",
      chatBgColor: "#111111",
      inputBgColor: "#1a1a1a",
      inputBorderColor: "#333333",
      inputFocusColor: "#d4af37",
      inputTextColor: "#f5f0e8",
      botTextColor: "#c9c0b3",
      userTextColor: "#d4af37",
      borderColor: "#333333",
      borderRadius: 12,
      inputRadius: 8,
      bubbleRadius: 12,
      shadow: "0 8px 40px rgba(212,175,55,0.15)",
    },
  },
  {
    name: "ocean",
    label: "Ocean",
    preview: "🌊",
    config: {
      primaryColor: "#0ea5e9",
      secondaryColor: "#0c4a6e",
      textColor: "#e0f2fe",
      headerBgColor: "#0c4a6e",
      headerTextColor: "#e0f2fe",
      botBubbleColor: "#0c4a6e",
      userBubbleColor: "#0369a1",
      chatBgColor: "#082f49",
      inputBgColor: "#0c4a6e",
      inputBorderColor: "#155e75",
      inputFocusColor: "#38bdf8",
      inputTextColor: "#e0f2fe",
      botTextColor: "#bae6fd",
      userTextColor: "#ffffff",
      borderColor: "#155e75",
      borderRadius: 16,
      inputRadius: 12,
      bubbleRadius: 16,
      shadow: "0 8px 40px rgba(14,165,233,0.2)",
    },
  },
  {
    name: "forest",
    label: "Forest",
    preview: "🌲",
    config: {
      primaryColor: "#16a34a",
      secondaryColor: "#14532d",
      textColor: "#dcfce7",
      headerBgColor: "#14532d",
      headerTextColor: "#dcfce7",
      botBubbleColor: "#14532d",
      userBubbleColor: "#166534",
      chatBgColor: "#052e16",
      inputBgColor: "#14532d",
      inputBorderColor: "#166534",
      inputFocusColor: "#22c55e",
      inputTextColor: "#dcfce7",
      botTextColor: "#bbf7d0",
      userTextColor: "#ffffff",
      borderColor: "#166534",
      borderRadius: 16,
      inputRadius: 12,
      bubbleRadius: 16,
      shadow: "0 8px 40px rgba(22,163,74,0.2)",
    },
  },
  {
    name: "sunset",
    label: "Sunset",
    preview: "🌅",
    config: {
      primaryColor: "#f97316",
      secondaryColor: "#431407",
      textColor: "#fff7ed",
      headerBgColor: "#431407",
      headerTextColor: "#fff7ed",
      botBubbleColor: "#431407",
      userBubbleColor: "#9a3412",
      chatBgColor: "#1c1008",
      inputBgColor: "#431407",
      inputBorderColor: "#7c2d12",
      inputFocusColor: "#fb923c",
      inputTextColor: "#fff7ed",
      botTextColor: "#fed7aa",
      userTextColor: "#ffffff",
      borderColor: "#7c2d12",
      borderRadius: 20,
      inputRadius: 14,
      bubbleRadius: 20,
      shadow: "0 8px 40px rgba(249,115,22,0.2)",
    },
  },
];

export function getThemeConfig(themeName: string): Record<string, string | number> {
  const theme = WIDGET_THEMES.find(t => t.name === themeName);
  return theme?.config || {};
}

export function applyTheme(currentConfig: Record<string, any>, themeName: string): Record<string, any> {
  const themeConfig = getThemeConfig(themeName);
  return { ...currentConfig, ...themeConfig, theme: themeName };
}
